"""Classification and matching experiments."""

from stroyhub.ml.category_queue import (
    CategoryLabelCandidate,
    CategoryLabelProduct,
    CategoryLabelQueue,
    CategoryLabelQueueItem,
)
from stroyhub.ml.datasets import (
    CategoryVerifierDatasetStatus,
    CategoryVerifierDatasetStore,
    CategoryVerifierSnapshot,
    CategoryVerifierSnapshotMetadata,
)
from stroyhub.ml.features import (
    CATEGORY_VERIFIER_FEATURE_SCHEMA_VERSION,
    CategoryVerifierCategoryInput,
    CategoryVerifierFeatureRow,
    CategoryVerifierProductInput,
    build_category_verifier_features,
)
from stroyhub.ml.labels import (
    CategoryLabelRecord,
    CategoryLabelStore,
    PredictorTarget,
    VerifierPairLabel,
)
from stroyhub.ml.matching import (
    MatchProduct,
    ProductMatchCandidate,
    ProductMatchReason,
    SourceProductLike,
    generate_product_match_candidates,
)
from stroyhub.ml.not_product_classifier import (
    NOT_PRODUCT_FEATURE_SCHEMA_VERSION,
    PATRON_MODEL_NAME,
    LinearNotProductClassifierModel,
    NotProductClassifierModel,
    NotProductClassifierModelUnavailableError,
    NotProductClassifierResult,
    NotProductExample,
    NotProductPrediction,
    PatronClassifier,
    build_not_product_text,
    load_not_product_examples,
    train_not_product_classifier_baseline,
    train_not_product_classifier_linear,
)
from stroyhub.ml.not_product_labels import (
    NotProductLabelRecord,
    NotProductLabelStore,
)
from stroyhub.ml.not_product_training import (
    NotProductEvaluation,
    NotProductEvaluationError,
    NotProductMetrics,
    NotProductSplit,
    NotProductSplitMetadata,
    NotProductTrainingResult,
    evaluate_not_product_classifier,
    split_not_product_examples,
    train_not_product_classifier_artifacts,
)
from stroyhub.ml.operator_decisions import (
    CategoryDecisionExample,
    CategoryPrediction,
    CategoryPredictionMetrics,
    NormalizationDecisionExample,
    NormalizationPrediction,
    NormalizationPredictionMetrics,
    OperatorDecisionDatasetBuilder,
    evaluate_category_predictions,
    evaluate_normalization_predictions,
    export_operator_decisions_jsonl,
)
from stroyhub.ml.patron_dataset import (
    PatronDatasetBuildResult,
    PatronLabelCandidate,
    build_patron_dataset_snapshot,
    patron_review_label_candidates,
)
from stroyhub.ml.runtime import (
    CategoryVerifier,
    CategoryVerifierModelUnavailableError,
    CategoryVerifierResult,
    CategoryVerifierThresholds,
)
from stroyhub.ml.training import (
    CategoryVerifierTrainingResult,
    InsufficientTrainingDataError,
    require_training_ready,
    train_category_verifier_from_snapshot,
)
from stroyhub.ml.verifier import (
    CategoryVerifierBaselineModel,
    CategoryVerifierExample,
    CategoryVerifierPrediction,
)

__all__ = [
    "MatchProduct",
    "ProductMatchCandidate",
    "ProductMatchReason",
    "CategoryLabelRecord",
    "CategoryLabelCandidate",
    "CategoryLabelProduct",
    "CategoryLabelQueue",
    "CategoryLabelQueueItem",
    "CategoryLabelStore",
    "NotProductLabelRecord",
    "NotProductLabelStore",
    "LinearNotProductClassifierModel",
    "NotProductClassifierModel",
    "NotProductClassifierModelUnavailableError",
    "NotProductClassifierResult",
    "NotProductEvaluation",
    "NotProductEvaluationError",
    "NotProductExample",
    "NotProductMetrics",
    "NotProductPrediction",
    "NotProductSplit",
    "NotProductSplitMetadata",
    "NotProductTrainingResult",
    "CategoryDecisionExample",
    "CategoryPrediction",
    "CategoryPredictionMetrics",
    "CategoryVerifierDatasetStatus",
    "CategoryVerifierDatasetStore",
    "CategoryVerifierCategoryInput",
    "CategoryVerifierFeatureRow",
    "CategoryVerifierProductInput",
    "CategoryVerifierBaselineModel",
    "CategoryVerifierExample",
    "CategoryVerifier",
    "CategoryVerifierModelUnavailableError",
    "CategoryVerifierPrediction",
    "CategoryVerifierResult",
    "CategoryVerifierSnapshot",
    "CategoryVerifierSnapshotMetadata",
    "CategoryVerifierThresholds",
    "CategoryVerifierTrainingResult",
    "CATEGORY_VERIFIER_FEATURE_SCHEMA_VERSION",
    "NOT_PRODUCT_FEATURE_SCHEMA_VERSION",
    "PATRON_MODEL_NAME",
    "InsufficientTrainingDataError",
    "NormalizationDecisionExample",
    "NormalizationPrediction",
    "NormalizationPredictionMetrics",
    "OperatorDecisionDatasetBuilder",
    "PatronDatasetBuildResult",
    "PatronClassifier",
    "PatronLabelCandidate",
    "PredictorTarget",
    "SourceProductLike",
    "VerifierPairLabel",
    "build_category_verifier_features",
    "build_not_product_text",
    "build_patron_dataset_snapshot",
    "evaluate_category_predictions",
    "evaluate_not_product_classifier",
    "evaluate_normalization_predictions",
    "export_operator_decisions_jsonl",
    "generate_product_match_candidates",
    "load_not_product_examples",
    "patron_review_label_candidates",
    "require_training_ready",
    "split_not_product_examples",
    "train_category_verifier_from_snapshot",
    "train_not_product_classifier_artifacts",
    "train_not_product_classifier_baseline",
    "train_not_product_classifier_linear",
]
