from dataclasses import dataclass


@dataclass(frozen=True, kw_only=True)
class NormalizedCategory:
    slug: str
    name: str
    parent_slug: str | None = None
    keywords: tuple[str, ...] = ()


def category(
    slug: str,
    name: str,
    *,
    parent_slug: str | None = None,
    keywords: tuple[str, ...] = (),
) -> NormalizedCategory:
    return NormalizedCategory(
        slug=slug,
        name=name,
        parent_slug=parent_slug,
        keywords=keywords,
    )


DEFAULT_NORMALIZED_CATEGORIES: tuple[NormalizedCategory, ...] = (
    category("mixes_aggregates", "Смеси и сыпучие материалы"),
    category("building_shell", "Конструкционные материалы"),
    category("sheet_board_materials", "Листовые и плитные материалы"),
    category("wood_materials", "Пиломатериалы и изделия из дерева"),
    category("metal_products", "Металлопрокат и металлические изделия"),
    category("roofing_facade", "Кровля, фасад и водосток"),
    category("insulation_waterproofing", "Изоляция и гидроизоляция"),
    category("paint_chemistry", "ЛКМ, клеи, пены и герметики"),
    category("interior_finishing", "Интерьер и отделка"),
    category("hardware", "Крепеж и метизы"),
    category("windows_doors", "Окна, двери и фурнитура"),
    category("plumbing_hvac", "Сантехника, отопление и вентиляция"),
    category("electrical", "Электрика и освещение"),
    category("tools_consumables", "Инструменты и расходные материалы"),
    category("outdoor_site", "Участок и наружное благоустройство"),
    category(
        "cement",
        "Цемент",
        parent_slug="mixes_aggregates",
        keywords=(
            "цемент",
            "портландцемент",
            "м500",
            "м400",
            "m500",
            "m400",
        ),
    ),
    category(
        "dry_mixes",
        "Сухие строительные смеси",
        parent_slug="mixes_aggregates",
        keywords=(
            "сухие смеси",
            "сухие строительные смеси",
            "сухая смесь",
            "пескобетон",
            "универсальная смесь",
        ),
    ),
    category(
        "plaster_mixes",
        "Штукатурки",
        parent_slug="mixes_aggregates",
        keywords=(
            "штукатурка",
            "штукатурки",
            "штукатурка гипсовая",
            "штукатурка цементная",
            "гипсовая штукатурка",
            "цементная штукатурка",
        ),
    ),
    category(
        "putty_mixes",
        "Шпаклевки",
        parent_slug="mixes_aggregates",
        keywords=(
            "шпаклевка",
            "шпатлевка",
            "шпатлевки",
            "шпаклевки",
            "шпатлевка готовая",
            "шпаклевка готовая",
        ),
    ),
    category(
        "floor_mixes",
        "Смеси для пола",
        parent_slug="mixes_aggregates",
        keywords=(
            "наливной пол",
            "пол наливной",
            "пол налив",
            "ровнитель",
            "стяжка",
            "смеси для пола",
            "покрытие для пола",
            "покрытие финиш",
            "полиуретановый пол",
        ),
    ),
    category(
        "tile_adhesives",
        "Плиточные клеи и затирки",
        parent_slug="mixes_aggregates",
        keywords=(
            "клей плиточный",
            "сухие клеевые смеси",
            "клеевые составы",
            "затирка",
            "затирки",
            "клей для плитки",
        ),
    ),
    category(
        "ready_mixes",
        "Готовые строительные составы",
        parent_slug="mixes_aggregates",
        keywords=(
            "готовые составы",
            "готовая смесь",
            "ремонтный состав",
        ),
    ),
    category(
        "aggregates",
        "Песок, щебень и сыпучие",
        parent_slug="mixes_aggregates",
        keywords=(
            "песок",
            "щебень",
            "гравий",
            "пгс",
            "отсев",
            "керамзит",
        ),
    ),
    category(
        "bricks_blocks",
        "Кирпич и строительные блоки",
        parent_slug="building_shell",
        keywords=(
            "кирпич",
            "блоки строительные",
            "газоблок",
            "пеноблок",
            "керамзитоблок",
            "блок строительный",
            "сибит",
        ),
    ),
    category(
        "reinforcement_mesh",
        "Арматура и кладочная сетка",
        parent_slug="building_shell",
        keywords=(
            "арматура",
            "кладочная сетка",
            "фиксаторы арматуры",
            "сетка кладочная",
        ),
    ),
    category(
        "building_ladders_scaffolds",
        "Леса, вышки и лестницы",
        parent_slug="building_shell",
        keywords=(
            "леса строительные",
            "вышки-туры",
            "вышки туры",
            "лестницы строительные",
            "стремянки",
            "чердачная лестница",
        ),
    ),
    category(
        "revision_hatches",
        "Люки и ревизионные решетки",
        parent_slug="building_shell",
        keywords=(
            "люки ревизионные",
            "люки и решетки",
            "ревизионный люк",
        ),
    ),
    category(
        "drywall",
        "Гипсокартон, ГВЛ и комплектующие",
        parent_slug="sheet_board_materials",
        keywords=(
            "гипсокартон",
            "гипсокартон и комплектующие",
            "гкл",
            "гвл",
            "гипсоволокнистые листы",
            "гипсокартонные листы",
        ),
    ),
    category(
        "cement_boards",
        "Аквапанели и огнезащитные листы",
        parent_slug="sheet_board_materials",
        keywords=(
            "аквапанель",
            "аквапанели",
            "огнезащитные листовые",
            "огнеупорные листовые",
            "стекломагнезитовые листы",
            "смл",
        ),
    ),
    category(
        "sip_panels",
        "СИП-панели",
        parent_slug="sheet_board_materials",
        keywords=(
            "сип панели",
            "сип-панели",
            "сип панель",
            "sip панели",
            "sip panel",
            "сэндвич панели",
            "сэндвич-панели",
        ),
    ),
    category(
        "osb_plywood_dsp",
        "Фанера, ОСП, ДВП и ДСП",
        parent_slug="sheet_board_materials",
        keywords=(
            "фанера",
            "осп",
            "osb",
            "дсп",
            "двп",
            "плита осп",
            "древесно-плитные",
            "мебельный щит",
        ),
    ),
    category(
        "polymer_sheets",
        "Полимерные и пластиковые листы",
        parent_slug="sheet_board_materials",
        keywords=(
            "листы полипропилен",
            "полипропилен лист",
            "поликарбонат",
            "оргстекло",
            "пластиковый лист",
        ),
    ),
    category(
        "glass_mirrors",
        "Стекло и зеркала",
        parent_slug="sheet_board_materials",
        keywords=(
            "стекло",
            "зеркало",
            "зеркала",
        ),
    ),
    category(
        "lumber",
        "Пиломатериалы",
        parent_slug="wood_materials",
        keywords=(
            "пиломатериал",
            "пиломатериалы",
            "доска",
            "брус",
            "рейка",
            "вагонка",
        ),
    ),
    category(
        "wood_decking",
        "Террасная доска и изделия из дерева",
        parent_slug="wood_materials",
        keywords=(
            "террасная доска",
            "изделия из дерева",
            "планкен",
            "ступень деревянная",
        ),
    ),
    category(
        "steel_profiles",
        "Профили, уголки и швеллеры",
        parent_slug="metal_products",
        keywords=(
            "уголок",
            "швеллер",
            "профильная труба",
            "труба профильная",
            "профиля",
            "профиль металлический",
            "полоса металлическая",
        ),
    ),
    category(
        "metal_sheets",
        "Металлические листы",
        parent_slug="metal_products",
        keywords=(
            "лист металлический",
            "алюминиевые листы",
            "латунные листы",
            "медные листы",
            "плоские листы",
            "мельхиор",
        ),
    ),
    category(
        "metal_pipes",
        "Металлические трубы",
        parent_slug="metal_products",
        keywords=(
            "трубы металлические",
            "металлическая труба",
            "труба стальная",
        ),
    ),
    category(
        "metal_mesh",
        "Металлические сетки",
        parent_slug="metal_products",
        keywords=(
            "сетка металлическая",
            "сетки металлические",
            "сетка от грызунов",
        ),
    ),
    category(
        "welding_materials",
        "Сварочные материалы",
        parent_slug="metal_products",
        keywords=(
            "электроды",
            "проволока сварочная",
            "сварочные материалы",
        ),
    ),
    category(
        "profiled_sheet",
        "Профлист и металлочерепица",
        parent_slug="roofing_facade",
        keywords=(
            "профлист",
            "профнастил",
            "металлочерепица",
            "профлист, металлочерепица",
            "профнастил с-",
            "профнастил мп-",
        ),
    ),
    category(
        "roofing_materials",
        "Скатная и рулонная кровля",
        parent_slug="roofing_facade",
        keywords=(
            "кровля",
            "скатная кровля",
            "ондулин",
            "шифер",
            "рубероид",
            "гибкая черепица",
            "плоская кровля",
            "кровельные материалы",
        ),
    ),
    category(
        "roofing_accessories",
        "Кровельные аксессуары",
        parent_slug="roofing_facade",
        keywords=(
            "снегозадержатель",
            "кровельные аксессуары",
            "ленты nicoband",
            "саморез кровельный",
            "саморезы кровельные",
        ),
    ),
    category(
        "drainage_systems",
        "Водосточные системы",
        parent_slug="roofing_facade",
        keywords=(
            "водосточная система",
            "водосточные системы",
            "водосток",
            "технониколь водосточная система пвх",
        ),
    ),
    category(
        "siding_facade_panels",
        "Сайдинг и фасадные панели",
        parent_slug="roofing_facade",
        keywords=(
            "сайдинг",
            "фасадные панели",
            "сайдинг, фасадные панели",
            "панель фасадная",
        ),
    ),
    category(
        "facade_tiles",
        "Фасадная плитка и системы",
        parent_slug="roofing_facade",
        keywords=(
            "фасадная плитка",
            "фасадные системы",
            "сетка фасадная",
        ),
    ),
    category(
        "mineral_wool",
        "Минеральная вата и минплита",
        parent_slug="insulation_waterproofing",
        keywords=(
            "минвата",
            "минеральная вата",
            "минплита",
            "минераловатный утеплитель",
            "изовер",
            "isover",
            "техноблок",
            "технотерм",
            "тисма",
        ),
    ),
    category(
        "foam_insulation",
        "Пенополистирол и XPS",
        parent_slug="insulation_waterproofing",
        keywords=(
            "пенополистирол",
            "экструдированный пенополистирол",
            "пеноплекс",
            "xps",
            "теплый дом",
        ),
    ),
    category(
        "natural_fiber_insulation",
        "Межвенцовые и натуральные утеплители",
        parent_slug="insulation_waterproofing",
        keywords=(
            "межвенцовый утеплитель",
            "утеплитель межвенцовый",
            "пакля",
            "пакля джутовая",
            "джутовая пакля",
            "джут",
            "экостен",
        ),
    ),
    category(
        "spray_polyethylene_insulation",
        "Напыляемая и полиэтиленовая изоляция",
        parent_slug="insulation_waterproofing",
        keywords=(
            "напыляемый утеплитель",
            "напыляемая теплоизоляция",
            "полиэтиленовая теплоизоляция",
        ),
    ),
    category(
        "vapor_barrier_membranes",
        "Мембраны и гидропароизоляция",
        parent_slug="insulation_waterproofing",
        keywords=(
            "гидропароизоляция",
            "мембраны",
            "изоспан",
            "экоспан",
            "пароизоляция",
            "ветрозащита",
            "изоляционные материалы",
        ),
    ),
    category(
        "waterproofing",
        "Гидроизоляция и мастики",
        parent_slug="insulation_waterproofing",
        keywords=(
            "гидроизоляция",
            "мастика гидроизоляционная",
            "жидкая резина",
            "обмазочная гидроизоляция",
            "аэрозольная гидроизоляция",
            "мастика",
        ),
    ),
    category(
        "geotextiles_fabrics",
        "Геотекстиль, стеклоткань и брезент",
        parent_slug="insulation_waterproofing",
        keywords=(
            "геотекстиль",
            "экоспан гео",
            "стеклоткань",
            "мат прошивной",
            "брезент",
            "брезент, войлок",
        ),
    ),
    category(
        "sealants",
        "Герметики",
        parent_slug="paint_chemistry",
        keywords=(
            "герметик",
            "герметики",
        ),
    ),
    category(
        "foams",
        "Монтажная пена",
        parent_slug="paint_chemistry",
        keywords=(
            "пена монтажная",
            "монтажная пена",
            "очистители пены",
        ),
    ),
    category(
        "construction_adhesives",
        "Клеи и жидкие гвозди",
        parent_slug="paint_chemistry",
        keywords=(
            "клей, жидкие гвозди",
            "жидкие гвозди",
            "клей монтажный",
            "клеевые стержни",
            "клей",
        ),
    ),
    category(
        "primers",
        "Грунтовки",
        parent_slug="paint_chemistry",
        keywords=(
            "грунтовка",
            "грунтовки",
            "грунты алкидные",
            "грунты водно-дисперсионные",
        ),
    ),
    category(
        "paints_enamels",
        "Краски и эмали",
        parent_slug="paint_chemistry",
        keywords=(
            "краска",
            "краски",
            "эмаль",
            "эмали",
            "аэрозольные эмали",
            "грунт-эмаль",
            "эмали аэрозольные",
            "краски düfa",
            "краски teknos",
            "краски командор",
        ),
    ),
    category(
        "varnishes_wood_protection",
        "Лаки, масла и деревозащита",
        parent_slug="paint_chemistry",
        keywords=(
            "лак",
            "лаки",
            "масла",
            "пропитка",
            "пропитки",
            "антисептик",
            "антисептики",
            "деревозащита",
            "огнебиозащита",
            "покрытия для дерева",
        ),
    ),
    category(
        "solvents_coloring",
        "Растворители и колеры",
        parent_slug="paint_chemistry",
        keywords=(
            "растворитель",
            "растворители",
            "колер",
            "колеры",
            "колоранты",
        ),
    ),
    category(
        "decorative_panels",
        "Панели ПВХ и МДФ",
        parent_slug="interior_finishing",
        keywords=(
            "декоративные панели",
            "панели пвх",
            "панели мдф",
            "пвх и мдф",
        ),
    ),
    category(
        "tile_porcelain",
        "Плитка и керамогранит",
        parent_slug="interior_finishing",
        keywords=(
            "керамическая плитка",
            "керамогранит",
            "плитка, керамогранит",
            "аксессуары для укладки плитки",
        ),
    ),
    category(
        "flooring",
        "Напольные покрытия",
        parent_slug="interior_finishing",
        keywords=(
            "напольные покрытия",
            "ламинат",
            "ламинаты",
            "линолеум",
            "подложки",
        ),
    ),
    category(
        "wallpaper",
        "Обои и обойный клей",
        parent_slug="interior_finishing",
        keywords=(
            "обои",
            "клей обойный",
            "обои, клей обойный",
        ),
    ),
    category(
        "ceilings",
        "Потолки",
        parent_slug="interior_finishing",
        keywords=(
            "потолки",
            "потолок подвесной",
            "подвесной потолок",
            "подвесные потолки",
        ),
    ),
    category(
        "decor_moulding",
        "Лепной декор",
        parent_slug="interior_finishing",
        keywords=(
            "лепной декор",
            "молдинг",
            "плинтус потолочный",
        ),
    ),
    category(
        "anchors",
        "Анкеры",
        parent_slug="hardware",
        keywords=(
            "анкер",
            "анкеры",
            "анкерный болт",
            "анкер-клин",
        ),
    ),
    category(
        "nails",
        "Гвозди и скобы",
        parent_slug="hardware",
        keywords=(
            "гвозд",
            "гвозди",
            "скобы строительные",
        ),
    ),
    category(
        "dowels",
        "Дюбели",
        parent_slug="hardware",
        keywords=(
            "дюбель",
            "дюбели",
            "дюбель-гвозд",
            "дюбель гвозд",
            "дюбель-хомут",
        ),
    ),
    category(
        "screws",
        "Саморезы и шурупы",
        parent_slug="hardware",
        keywords=(
            "саморез",
            "саморезы",
            "шуруп",
            "шурупы",
            "саморезы стеновые",
        ),
    ),
    category(
        "metric_fasteners",
        "Метрический крепеж",
        parent_slug="hardware",
        keywords=(
            "болт",
            "болты",
            "гайка",
            "гайки",
            "шайба",
            "шайбы",
            "шпилька",
            "метрический крепеж",
        ),
    ),
    category(
        "perforated_fasteners",
        "Перфорированный и скрытый крепеж",
        parent_slug="hardware",
        keywords=(
            "перфорация",
            "крепеж перфорированный",
            "скрытый крепеж",
            "опоры бруса",
            "пластины",
            "уголки",
        ),
    ),
    category(
        "rigging_clamps_ties",
        "Такелаж, хомуты и стяжки",
        parent_slug="hardware",
        keywords=(
            "такелаж",
            "хомут",
            "хомуты",
            "стяжки",
            "трос",
            "цепи",
            "карабины",
        ),
    ),
    category(
        "doors",
        "Двери",
        parent_slug="windows_doors",
        keywords=(
            "двери",
            "двери входные",
            "двери межкомнатные",
            "двери технические",
            "двери противопожарные",
            "двери балконные",
            "двери печные",
        ),
    ),
    category(
        "windows",
        "Окна и комплектующие",
        parent_slug="windows_doors",
        keywords=(
            "окна",
            "окна пластиковые",
            "окна veka",
            "оконные комплектующие",
        ),
    ),
    category(
        "door_window_hardware",
        "Дверная и оконная фурнитура",
        parent_slug="windows_doors",
        keywords=(
            "замочно-скобяные",
            "замок",
            "ручка дверная",
            "петли дверные",
            "козырьки",
        ),
    ),
    category(
        "sewer_pipes",
        "Канализация",
        parent_slug="plumbing_hvac",
        keywords=(
            "канализация",
            "трубы канализационные",
            "фитинги канализационные",
            "трубы и фитинги канализационные",
            "отводы канализационные",
        ),
    ),
    category(
        "water_pipes_fittings",
        "Водопроводные трубы и фитинги",
        parent_slug="plumbing_hvac",
        keywords=(
            "трубы и фитинги",
            "трубы полипропиленовые",
            "фитинги полипропиленовые",
            "трубы металло-пластиковые",
            "фитинги латунные",
            "подводка для воды",
        ),
    ),
    category(
        "heating",
        "Отопление",
        parent_slug="plumbing_hvac",
        keywords=(
            "радиаторы",
            "радиаторы отопления",
            "водонагреватели",
            "полотенцесушители",
            "теплоносители",
            "печи",
            "камины",
            "котлы",
            "тэн",
        ),
    ),
    category(
        "ventilation",
        "Вентиляция",
        parent_slug="plumbing_hvac",
        keywords=(
            "вентиляция",
            "вентиляционные решетки",
            "воздуховод",
        ),
    ),
    category(
        "water_filters_tanks",
        "Фильтры и баки для воды",
        parent_slug="plumbing_hvac",
        keywords=(
            "фильтры для воды",
            "водоочистители",
            "баки для воды",
            "бочки,баки",
            "бочки",
            "баки",
        ),
    ),
    category(
        "sanitary_ware",
        "Сантехника и санфаянс",
        parent_slug="plumbing_hvac",
        keywords=(
            "сантехника",
            "унитаз",
            "унитазы",
            "раковина",
            "раковины",
            "ванны",
            "душевые кабины",
            "смесители",
            "мойки для кухни",
            "сифоны",
        ),
    ),
    category(
        "cables_wires",
        "Кабели и провода",
        parent_slug="electrical",
        keywords=(
            "кабели",
            "провода",
            "кабели и провода",
            "кабель",
        ),
    ),
    category(
        "cable_routing",
        "Кабеленесущие системы",
        parent_slug="electrical",
        keywords=(
            "кабель-канал",
            "кабель-каналы",
            "кабельные лотки",
            "металлорукав",
            "системы прокладки кабеля",
            "трубы для прокладки кабеля",
        ),
    ),
    category(
        "wiring_devices",
        "Розетки, выключатели и коробки",
        parent_slug="electrical",
        keywords=(
            "розетки",
            "выключатели",
            "звонок электрический",
            "звонки электрические",
            "подрозетники",
            "монтажные коробки",
            "электроустановочные изделия",
            "рамки",
            "накладки",
        ),
    ),
    category(
        "electrical_panels",
        "Электрощитовое оборудование",
        parent_slug="electrical",
        keywords=(
            "электрощитовое оборудование",
            "щит",
            "автоматический выключатель",
            "узо",
            "дифавтомат",
        ),
    ),
    category(
        "lighting",
        "Освещение",
        parent_slug="electrical",
        keywords=(
            "освещение",
            "светильник",
            "светильники",
            "лампы",
            "прожектор",
        ),
    ),
    category(
        "power_extensions",
        "Удлинители и сетевые фильтры",
        parent_slug="electrical",
        keywords=(
            "удлинители",
            "сетевые фильтры",
            "тройники",
            "шнуры",
            "разветвители",
        ),
    ),
    category(
        "power_tool_accessories",
        "Оснастка для электроинструмента",
        parent_slug="tools_consumables",
        keywords=(
            "аксессуары для электроинструмента",
            "диски алмазные",
            "диски отрезные",
            "биты",
            "буры",
            "сверла",
            "коронки",
            "щетки и корщетки",
        ),
    ),
    category(
        "power_tools",
        "Электроинструмент",
        parent_slug="tools_consumables",
        keywords=(
            "электроинструменты",
            "дрели",
            "шуруповерты",
            "перфораторы",
            "лобзики",
            "пилы",
            "шлифовальные машинки",
            "штроборезы",
            "фены строительные",
        ),
    ),
    category(
        "hand_tools",
        "Ручной инструмент",
        parent_slug="tools_consumables",
        keywords=(
            "ручные инструменты",
            "строительный инструмент",
            "инструмент строительный",
            "отвертки",
            "ножи",
            "молотки",
            "ключи",
            "ножовки",
            "плиткорезы",
            "столярный и слесарный инструмент",
        ),
    ),
    category(
        "measuring_tools",
        "Измерительный инструмент",
        parent_slug="tools_consumables",
        keywords=(
            "измерительный инструмент",
            "рулетки",
            "уровни",
            "штангенциркуль",
            "линейки",
            "угольники",
            "дальномер",
        ),
    ),
    category(
        "painting_plastering_tools",
        "Малярный и штукатурный инструмент",
        parent_slug="tools_consumables",
        keywords=(
            "малярный инструмент",
            "штукатурный инструмент",
            "краскопульт",
            "краскопульты",
            "валики",
            "кисти",
            "шпатели",
            "кельмы",
            "гладилки",
            "правила",
            "терки",
        ),
    ),
    category(
        "protective_equipment",
        "Средства защиты",
        parent_slug="tools_consumables",
        keywords=(
            "средства защиты",
            "перчатки",
            "очки защитные",
            "респиратор",
        ),
    ),
    category(
        "abrasives_tapes_consumables",
        "Абразивы, ленты и расходники",
        parent_slug="tools_consumables",
        keywords=(
            "расходные материалы",
            "шлифовальная бумага",
            "ленты, сетки, скотчи",
            "скотч",
            "абразивные сетки",
            "круги шлифовальные",
        ),
    ),
    category(
        "garden_tools",
        "Садовый инструмент",
        parent_slug="outdoor_site",
        keywords=(
            "садовый инструмент",
            "садовый инвентарь",
            "лопаты",
            "грабли",
            "тачки",
            "товары для полива",
        ),
    ),
    category(
        "greenhouses",
        "Теплицы",
        parent_slug="outdoor_site",
        keywords=(
            "теплицы",
            "удлинители для теплиц",
            "теплицы и удлинители для теплиц",
        ),
    ),
    category(
        "paving_borders",
        "Тротуарная плитка и бордюры",
        parent_slug="outdoor_site",
        keywords=(
            "плитка тротуарная",
            "бордюр тротуарный",
            "полимерпесчаные изделия",
        ),
    ),
)


def get_normalized_category(slug: str) -> NormalizedCategory | None:
    for normalized_category in DEFAULT_NORMALIZED_CATEGORIES:
        if normalized_category.slug == slug:
            return normalized_category
    return None


def iter_root_categories() -> tuple[NormalizedCategory, ...]:
    return tuple(
        normalized_category
        for normalized_category in DEFAULT_NORMALIZED_CATEGORIES
        if normalized_category.parent_slug is None
    )


def iter_leaf_categories() -> tuple[NormalizedCategory, ...]:
    return tuple(
        normalized_category
        for normalized_category in DEFAULT_NORMALIZED_CATEGORIES
        if normalized_category.keywords
    )
