"""add is_not_product to source_products

Revision ID: fe917260ca58
Revises: 20260522_0004
Create Date: 2026-05-22 16:34:34.163442
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = 'fe917260ca58'
down_revision: str | None = '20260522_0004'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'source_products',
        sa.Column('is_not_product', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('source_products', 'is_not_product')
    # ### end Alembic commands ###
